version: "3.9"

services:
  canteen:
    container_name: canteen
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DBHOST: ${POSTGRES_DBHOST}
      POSTGRES_DBPORT: ${POSTGRES_DBPORT}
      DJANGO_SECRETKEY: ${DJANGO_SECRETKEY}
    volumes:
      - ./Canteen:/Canteen
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: