version: "3.9"

services:
  canteen:
    container_name: canteen
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      MARIA_DB: ${MARIA_DB}
      MARIA_USER: ${MARIA_USER}
      MARIA_PASSWORD: ${MARIA_PASSWORD}
      MARIA_DBHOST: ${MARIA_DBHOST}
      MARIA_DBPORT: ${MARIA_DBPORT}
      DJANGO_SECRETKEY: ${DJANGO_SECRETKEY}
    volumes:
      - ./Canteen:/Canteen
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIA_DB}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MARIA_PASSWORD}
      # CREATE USER 'freesia'@'%' IDENTIFIED BY '비밀번호';
      # mariadb p-uroot -p
      # GRANT ALL PRIVILEGES ON *.* TO 'freesia'@'%' WITH GRANT OPTION;
      # FLUSH PRIVILEGES;
    volumes:
      - D:/data/mariadb/data/:/var/lib/mysql